### PR TITLE
Issue 56 - Identities - Unique VendorUniqueKey with same SyncName

### PR DESCRIPTION
**Pull request by TonyMasse**
## Issue:
In response to Issue #56 
**Add-LrIdentity - Using SyncName to generate VendorUniqueKey prevent multiple users being added with the same SyncName**

## What does it do?
I propose to use `SyncName `a dash and a some random characters to generate the `VendorUniqueKey`. That way it's always different and prevent one Identity creation from overriding another one already created with the same `SyncName`.

## Commits
Just one:

**Randomise `VendorUniqueKey `to avoid problems when multiple Identities are being pushed with the same `SyncName`**
Added a random number of charachers added to the end of $SyncName

### CODE REVIEW

**Comment by GeneCupstid** [comment]
@TonyMasse - do you use Slack or Discord or something similar where we can collaborate?

**Comment by TonyMasse** [comment]
Hi,

I’d like to, but I never did use any of these tools.
And when trying to get access to your Slack I didn’t exactly go very far.

Regards,
Tony
[SNIP]

**Comment by TonyMasse** [comment]
@GeneCupstid , @Jt3kt - what Workspace are you guys using on Slack?
In case, please invite me (I'm using tony.masse@logrhythm.com).
Thx

**Comment by Jt3kt** [comment]
Hey Tony,

I sent an invite over your way.  You'll find a channel there #LogRhythm-Tools.

Thanks,
Eric

**Pull request merged**
